<?php

if (!module_exists('xautoload')) {
  spl_autoload_register('_amazee_crumbs_autoload');
}

/**
 * Autoload callback.
 */
function _amazee_crumbs_autoload($class) {
  if (preg_match('#^amazee_crumbs_(.*)$#', $class, $matches)) {
    module_load_include('php', 'amazee_crumbs', 'lib/' . strtr($matches[1], '_', '/'));
  }
}

/**
 * Implements hook_crumbs_plugins().
 *
 * @param crumbs_InjectedAPI_hookCrumbsPlugins $api
 */
function amazee_crumbs_crumbs_plugins($api) {
  $plugin = new amazee_crumbs_MonoPlugin_FirstPathFromActiveTrail();
  $api->monoPlugin('firstPathFromActiveTrail', $plugin);

  $plugin = new amazee_crumbs_MonoPlugin_NodeTitle();
  $api->monoPlugin('nodeTitle', $plugin);
}

/**
 * Implements hook_query_TAG_alter().
 */
function amazee_crumbs_query_crumbs_select_menu_links_alter(QueryAlterableInterface $query) {
  if ($query instanceof SelectQuery) {
    $main_menu_name = _amazee_crumbs_get_active_main_menu_name();
    if ($main_menu_name) {
      foreach ($query->getTables() as $table) {
        if ($table['table'] == 'menu_links') {
          $query->condition($table['alias'] . '.menu_name', $main_menu_name);
        }
      }
    }
  }
}

/**
 * Returns currently active main menu.
 *
 * Works only if $conf['amazee_crumbs_main_menu_mini_panel'] is set.
 *
 * @return string|null
 *   Menu machine name or NULL.
 */
function _amazee_crumbs_get_active_main_menu_name() {
  $cache =& drupal_static(__FUNCTION__, FALSE);
  if ($cache === FALSE) {
    $cache = NULL;
    $main_menu_mini_panel = variable_get('amazee_crumbs_main_menu_mini_panel');
    if ($main_menu_mini_panel) {
      $mini = panels_mini_load($main_menu_mini_panel);
      if ($mini) {
        ctools_include('plugins', 'panels');
        /** @var panels_display $display */
        $display = $mini->display;
        foreach ($display->content as $pane) {
          if (strpos($pane->subtype, 'superfish-') === 0) {
            if (panels_pane_access($pane, $display)) {
              list(, $superfish_id) = explode('-', $pane->subtype);
              list($main_menu_name) = explode(':', variable_get('superfish_menu_' . $superfish_id));
              $cache = $main_menu_name;
              break;
            }
          }
        }
      }
    }
  }
  return $cache;
}
